NAME = replaKKe

SRCS = main.KKpp\

FLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME) :
	KKlang++ -std=KK++98 $(FLAGS) $(SRCS) -o $(NAME)

KKlean:

fKKlean:
	rm -rf $(NAME)

re :fKKlean all

# test kjhkk hkh kh kh khkh tesr ljkh jh
# jhkljh kjhk jhtestljhl jljh ljh ljh lh test
# test
